from enum import Enum


class YellowLetters(Enum):
        a = ":Aj:"
        b = ":Bj:"
        c = ":Cj:"
        d = ":Dj:"
        e = ":Ej:"
        f = ":Fj:"
        g = ":Gj:"
        h = ":Hj:"
        i = ":Ij:"
        j = ":Jj:"
        k = ":Kj:"
        l = ":Lj:"
        m = ":Mj:"
        n = ":Nj:"
        o = ":Oj:"
        p = ":Pj:"
        q = ":Qj:"
        r = ":Rj:"
        s = ":Sj:"
        t = ":Tj:"
        u = ":Uj:"
        v = ":Vj:"
        w = ":Wj:"
        x = ":Xj:"
        y = ":Yj:"
        z = ":Zj:"